# Generated by Django 4.2.3 on 2023-07-17 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Researchers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'researchers',
            },
        ),
        migrations.CreateModel(
            name='UserDet',
            fields=[
                ('phone', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'userdet',
            },
        ),
        migrations.CreateModel(
            name='DocDet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'docdet',
            },
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.IntegerField()),
                ('age', models.IntegerField()),
                ('history', models.IntegerField()),
                ('hypertension', models.IntegerField()),
                ('inactivity', models.IntegerField()),
                ('cardiovascular', models.IntegerField()),
                ('hyperlidermia', models.IntegerField()),
                ('alcohol', models.IntegerField()),
                ('tia', models.IntegerField()),
                ('msyndrome', models.IntegerField()),
                ('atherosclerosis', models.IntegerField()),
                ('af', models.IntegerField()),
                ('lvh', models.IntegerField()),
                ('diabetes', models.IntegerField()),
                ('smoking', models.IntegerField()),
                ('stroke', models.IntegerField()),
                ('advice', models.TextField()),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predictor.userdet')),
            ],
            options={
                'db_table': 'data',
            },
        ),
    ]
